- name: Enable stonith
  command: pcs property set stonith-enabled=true
  register: stonith
  changed_when: "'error' not in stonith.stdout"
  run_once: true

- name: Create stonith device without host mapping
  command: >
    pcs stonith create {{ sap_hana_ha_pacemaker_fencing_device.name }} {{ sap_hana_ha_pacemaker_fencing_device.type }}
    ipaddr={{ sap_hana_ha_pacemaker_fencing_device.ip }} login={{ sap_hana_ha_pacemaker_fencing_device.user }}
    passwd={{ sap_hana_ha_pacemaker_fencing_device.pwd }}  pcmk_host_list={{ sap_hana_ha_pacemaker_fencing_device.host_list }} op monitor interval=30
  when:
    - sap_hana_ha_pacemaker_fencing_device_type != "fence_azure_arm"
    - not( sap_hana_ha_pacemaker_fencing_device.host_list is none )
  register: stonith_device
  changed_when: "'error' not in stonith_device.stdout"
  run_once: true

- name: Create stonith device with host mapping
  command: >
    pcs stonith create {{ sap_hana_ha_pacemaker_fencing_device.name }} fence_ipmilan
    ipaddr={{ sap_hana_ha_pacemaker_fencing_device.ip }} login={{ sap_hana_ha_pacemaker_fencing_device.user }}
    passwd={{ sap_hana_ha_pacemaker_fencing_device.pwd }}  pcmk_host_map={{ sap_hana_ha_pacemaker_fencing_device.host_list_map }} op monitor interval=30
  when:
    - sap_hana_ha_pacemaker_fencing_device.type != "fence_azure_arm"
    - not( sap_hana_ha_pacemaker_fencing_device.host_list_map is none )
  register: stonith_device
  changed_when: "'error' not in stonith_device.stdout"
  run_once: true